import type { Metadata } from 'next';
<<<<<<< HEAD

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
=======

import MyProvider from './_provider/provider';

export const metadata: Metadata = {
  title: 'DoGo Project',
  description: '호텔 숙박 시설 중개 애플리케이션입니다.'
>>>>>>> 6ea6f7794bae6e71069afdc52a8c2bbc6eb5793e
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body>{children}</body>
=======
    <html lang="ko">
      <MyProvider>
        <body>{children}</body>
      </MyProvider>
>>>>>>> 6ea6f7794bae6e71069afdc52a8c2bbc6eb5793e
    </html>
  );
}
